<a href="https://colab.research.google.com/github/RimbaParamukti/Analyzing-TransJakarta-Ridership-Data/blob/main/Final_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import pandas as pd
import numpy

In [8]:
df = pd.read_csv('/content/Transjakarta.csv',sep=',')
df
df[df['payCardSex'] == 'M']

,transID,payCardID,payCardBank,payCardName,payCardSex,payCardBirthDate,corridorID,corridorName,direction,tapInStops,...,tapInStopsLon,stopStartSeq,tapInTime,tapOutStops,tapOutStopsName,tapOutStopsLat,tapOutStopsLon,stopEndSeq,tapOutTime,payAmount
0,EIIW227B8L34VB,180062659848800,emoney,Bajragin Usada,M,2008,5,Matraman Baru - Ancol,1.0,P00142,...,106.84402,7,2023-04-03 05:21:44,P00253,Tegalan,-6.203101,106.85715,12.0,2023-04-03 06:00:53,3500.0
4,VMLO535V7F95NJ,570928206772,flazz,Embuh Mardhiyah,M,1982,12,Tanjung Priok - Pluit,0.0,P00239,...,106.88900,5,2023-04-03 06:17:35,P00098,Kali Besar Barat,-6.135355,106.81143,15.0,2023-04-03 06:57:03,3500.0
6,HEMW326B9N91TV,213155822653833,emoney,"R. Devi Hariyah, S.T.",M,1974,JAK.18,Kalibata - Kuningan,0.0,B00243P,...,106.85165,25,2023-04-03 06:58:21,NaN,NaN,NaN,NaN,NaN,NaN,0.0
9,ERXO372B2H63RB,3580401035990896,dki,"T. Dadap Pradana, M.Ak",M,2004,1Q,Rempoa - Blok M,0.0,B05781P,...,106.77889,15,2023-04-03 05:57:47,B06578P,Blok M Jalur 3,-6.243426,106.80188,24.0,2023-04-03 06:51:12,3500.0
14,LZFD368Q3E81HJ,4056836188316,online,Nadine Utami,M,1975,JAK.46,Pasar Minggu - Jagakarsa,1.0,B00608P,...,106.83787,5,2023-04-03 05:38:44,B01062P,Jln. Gabus Raya,-6.301222,106.83623,17.0,2023-04-03 06:09:17,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37885,KUXY021D6I25YN,30169751274025,bni,Prasetya Wasita,M,1986,3B,NaN,1.0,B04610P,...,106.72736,2,2023-04-08 10:46:06,B00192P,BSI Cengkareng,-6.147973,106.72781,3.0,2023-04-08 13:06:42,0.0
37889,FSZU331F3O29PS,4300800810103,online,Faizah Samosir,M,2009,JAK.18,Kalibata - Kuningan,0.0,B01450P,...,106.84661,8,2023-04-30 07:22:58,NaN,Gg. Trijaya IV Tebet Timur,-6.232163,106.85280,20.0,2023-04-30 09:10:03,0.0
37892,YHJT665I6G08OS,4775206940093,online,"Cahyo Sudiati, M.Farm",M,1979,JAK.52,Terminal Kalideres - Terminal Muara Angke,1.0,B01087P,...,106.73712,29,2023-04-28 16:38:56,B03207P,RSUD Cengkareng,-6.142238,106.73398,30.0,2023-04-28 18:35:16,0.0
37896,YHHK837P6Y95GN,6502902290603767,dki,Titi Siregar,M,1974,9N,Pinang Ranti - Pramuka,1.0,P00064,...,106.88116,1,2023-04-18 21:52:31,P00179,Pinang Ranti,-6.291075,106.88634,2.0,2023-04-18 22:28:22,3500.0
37898,RGVK175U2U98UV,377840859133591,emoney,Ana Agustina,M,1976,JAK.13,Tanah Abang - Jembatan Lima,1.0,B02505P,...,106.80954,33,2023-04-15 19:59:26,B01787P,JPO Blok G,-6.188861,106.81135,34.0,2023-04-15 20:27:50,0.0

In [ ]:
df.info()

**ADD GENERASI**

In [ ]:
def gencek(collection):
    if (collection['payCardBirthDate'] >= 1946) & (collection['payCardBirthDate'] < 1964):
      generasi = 'Baby Boomers'
    elif (collection['payCardBirthDate'] >= 1964) & (collection['payCardBirthDate'] < 1980):
      generasi = 'Generasi X'
    elif (collection['payCardBirthDate'] >= 1980) & (collection['payCardBirthDate'] < 2000):
      generasi = 'Generasi Y'
    elif (collection['payCardBirthDate'] >= 2000):
      generasi = 'Generasi Z'
    else:
      generasi = 'Tidak ada Data'
    return generasi


df['Generasi'] = df.apply(gencek, axis=1)
df

**Perubahan payCard SEX**

In [ ]:
def ubahjeniskelamin(sex):
  if sex == 'F':
    return 'Female'
  elif sex == 'M':
    return 'Male'
  else:
    return 'Unknown'

df['payCardSex'] = df['payCardSex'].apply(ubahjeniskelamin)
df

**Jumlah Pemberhentian**

In [ ]:
def JumlahPemberhentian(collection):
    Jumlah = collection['stopEndSeq'] -collection['stopStartSeq']
    return Jumlah


df['JumlahPemberhentian'] = df.apply(JumlahPemberhentian, axis=1)
df

**Upload Code**

In [ ]:
from google.colab import files